[project]
name = "crawl-news"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "crawl4ai>=0.6.3",
    "litellm>=1.70.4",
    "pydantic>=2.11.5",
    "python-dotenv>=1.1.0",
]
